export const Colors = {
  basic: "#424242",
  //  basicDark: "#2e2e2e",
  basicDark: "#212121",
  basicLight: "#676767",
  navColor: "#fff",
  navText: "#212121",
  //  navTextActive: "#fff",
  navTextActive: "#fff",
  //  second: "#3f51b5",
  second: "#424242",
  //  second: "#ffee58",
  //  secondDark: "#2c387e",
  //  secondDark: "#fdd835",
  secondDark: "#212121",
  //  secondLight: "#6573c3",
  //  secondLight: "#fff59d",
  secondLight: "#616161",
  background: "red",
  //  textBacis: "#212121",
  textBacis: "#fff",
  // textBasic: "#fff",
  textBackground: "#212121",
  secondRgb: "255, 87, 34",
  headerText: "#fff",
}

export const Routes = [
  {
    id: 0,
    name: "O nas",
    link: "/",
    icon: "IoMdHome",
  },
  {
    id: 1,
    name: "Sklep online",
    link: "/shop",
    icon: "MdShoppingCart",
  },
  // {
  //   id: 2,
  //   name: "Wyceń okulary",
  //   link: "/products",
  //   icon: "MdShoppingCart",
  // },
  {
    id: 3,
    name: "Aktualności i Promocj",
    link: "/promotions",
    icon: "FaImages",
  },
  {
    id: 4,
    name: "Kontakt",
    link: "/contact",
    icon: "MdPhoneIphone",
  },
]
